"""Security primitives re-exported for design-doc alignment (`core/security.py`)."""

from app.security import (
    MAX_PASSWORD_LENGTH,
    MIN_PASSWORD_LENGTH,
    TokenError,
    TokenExpiredError,
    TokenInvalidError,
    bearer_token_from_header,
    constant_time_equals,
    create_access_token,
    decode_access_token,
    generate_jti,
    generate_refresh_token,
    generate_secure_secret,
    get_access_token_expires_in,
    get_refresh_token_ttl,
    hash_password,
    hash_refresh_token,
    needs_rehash,
    redact_secret,
    refresh_token_expires_at,
    scrub_sensitive,
    verify_password,
)

__all__ = [
    "MAX_PASSWORD_LENGTH",
    "MIN_PASSWORD_LENGTH",
    "TokenError",
    "TokenExpiredError",
    "TokenInvalidError",
    "bearer_token_from_header",
    "constant_time_equals",
    "create_access_token",
    "decode_access_token",
    "generate_jti",
    "generate_refresh_token",
    "generate_secure_secret",
    "get_access_token_expires_in",
    "get_refresh_token_ttl",
    "hash_password",
    "hash_refresh_token",
    "needs_rehash",
    "redact_secret",
    "refresh_token_expires_at",
    "scrub_sensitive",
    "verify_password",
]
